# MariaDB - install

- name: Install MariaDB
  openbsd_pkg: state=present name=mariadb-server

- name: Detect default database
  stat:
    path: /var/mysql
  register: mysql_directory

- name: Create default database
  command: /usr/local/bin/mysql_install_db
  when: not mysql_directory.stat.exists

- name: Configure MariaDB listen address
  lineinfile:
    path: /etc/my.cnf
    regexp: '^bind-address'
    line: 'bind-address = 0.0.0.0'

- name: Configure access for root
  action: template src=my.cnf.j2 dest=/root/.my.cnf

- name: Start MariaDB
  service:
    name: mysqld
    state: started
    enabled: yes

- name: Install Percona toolkit
  openbsd_pkg: state=present name=percona-toolkit

- name: Python MySQL module dependency for mysql_db / mysql_user
  openbsd_pkg: state=present name=py-mysql
