# MariaDB - secure

# The heredoc answers these questions
# - Enter current password for root (enter for none):
# - Set root password? [Y/n]
# - New password:
# - Re-enter new password:
# - Remove anonymous users? [Y/n]
# - Disallow root login remotely? [Y/n]
# - Remove test database and access to it? [Y/n]
# - Reload privilege tables now? [Y/n]

- name: Detect mysql test directory
  stat:
    path: /var/mysql/test
  register: mysql_test_directory

- name: Secure MariaDB installation
  shell:
    cmd: |
      mysql_secure_installation <<EOF


      vagrant
      vagrant



      EOF
  when: mysql_test_directory.stat.exists
